language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpcs -sp --standard=psr2 src
  # - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  # - wget https://scrutinizer-ci.com/ocular.phar
  # - php ocular.phar code-coverage:upload --format=php-clover build/coverage/log/coverage.xml

notifications:
  email: false
