language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.3

install:
  - composer self-update
  - composer install

before_script:
  - export GH_AUTHOR=$(git log --pretty=format:"%aN" -1)
  - export GH_EMAIL=$(git log --pretty=format:"%aE" -1)
  - export GH_REV=$(git rev-parse --short HEAD)

script:
  - make test

after_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then make coverage; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then make docs; fi

notifications:
  email: false
